version: "3"
services:
  app:
    container_name: node_app
    build: ./
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules/
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"

